# Generated by Django 4.0.5 on 2022-10-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_homework'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
