# Generated by Django 4.0.5 on 2022-10-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='on_going',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
