# Generated by Django 4.0.5 on 2022-10-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_books_on_going'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='on_going',
        ),
    ]
