# Generated by Django 4.0.5 on 2022-10-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_remove_books_on_going'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='is_finished',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
