# Generated by Django 4.0.5 on 2022-10-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_remove_books_status_books_is_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
