# Generated by Django 4.0.5 on 2022-12-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_diary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
