# Generated by Django 4.0.5 on 2022-12-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.TextField()),
                ('book', models.FileField(upload_to='books')),
            ],
        ),
    ]
