# Generated by Django 4.0.5 on 2022-12-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('music', models.FileField(upload_to='music/')),
            ],
        ),
    ]
