# Generated by Django 4.0.5 on 2022-12-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_music'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
