# Generated by Django 4.0.5 on 2022-12-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_todocss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todocss',
        ),
    ]
