# Generated by Django 4.0.4 on 2022-12-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
