# Generated by Django 4.0.4 on 2023-01-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
