# Generated by Django 4.0.4 on 2023-01-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_finished',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='pexels.jpg', upload_to='profilepics'),
        ),
    ]
