# Generated by Django 4.0.4 on 2023-01-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_books_is_finished_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
