# Generated by Django 4.0.4 on 2023-01-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_alter_books_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='is_finished',
        ),
    ]
