# Generated by Django 4.0.4 on 2023-01-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
