# Generated by Django 4.0.4 on 2023-02-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_remove_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='is_finished',
        ),
    ]
